// file: src/renderer/src/definitions/commands/core/help.ts
import { CommandDefinition } from '../types'
import { coreCommands } from "@/renderer/definitions/commands/core/index.ts";

// Note: In the future, this could be dynamically generated by the command loader.
const helpText = 'Available commands: ';

export const helpCommand: CommandDefinition = {
  name: 'help',
  description: 'Displays a list of available commands.',
  soundBlueprint: {
    sources: [{ type: 'oscillator', oscillatorType: 'sine', frequency: 440 }],
    envelope: { attack: 0.01, decay: 0.1, sustain: 0.2, release: 0.1 },
    duration: 0.4
  },
  execute: (_args = []) => ({
    output: helpText + coreCommands.map(cmd => cmd.name).join(', ')
  })
}
