import { CommandDefinition } from '../types'

// Note: In the future, this could be dynamically generated by the command loader.
const helpText = 'Available commands: clear, help, test:error, toggle:latency'

export const helpCommand: CommandDefinition = {
  name: 'help',
  description: 'Displays a list of available commands.',
  staticSoundEvents: ['commandSuccess'],
  execute: () => ({
    output: helpText
  })
}
