// file: src/renderer/src/definitions/commands/core/help.ts
import { CommandDefinition } from '../types'

// Note: In the future, this could be dynamically generated by the command loader.
const helpText = 'Available commands: clear, help, test:error, toggle:latency'

export const helpCommand: CommandDefinition = {
  name: 'help',
  description: 'Displays a list of available commands.',
  soundBlueprint: {
    sources: [{ type: 'oscillator', oscillatorType: 'sine', frequency: 440 }],
    envelope: { attack: 0.01, decay: 0.1, sustain: 0.2, release: 0.1 },
    duration: 0.4
  },
  execute: () => ({
    output: helpText
  })
}