# .github/workflows/build.yml
name: Build Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            build_script: build:mac
            artifact_path: dist/mac/
          - os: windows-latest
            build_script: build:win
            artifact_path: dist/win/
          - os: ubuntu-latest
            build_script: build:linux
            artifact_path: dist/linux/

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci

      # 🚀 Cache node_modules
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm        # npm cache (speeds up npm install/ci)
            node_modules  # your dependencies
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # Build the app (renderer + main) for Electron
      - name: Build Electron App for platform
        run: npm run ${{ matrix.build_script }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-installer
          path: dist/
